@host=https://localhost:7291


GET {{host}}/bp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MDg1MWViOC1mOTZjLTQ5N2ItOTVmOS03MDdjZTE5Yjk3ZGUiLCJqdGkiOiJjOGVjYTZiMi00MDEzLTQ3YmMtOWQ0MS1hZWQ1OWM0NTEwZDUiLCJnaXZlbl9uYW1lIjoiTWljaGFlbCIsImZhbWlseV9uYW1lIjoiUHJhdHRpbmdlciIsImV4cCI6MTcyNjQ5NzUyMCwiaXNzIjoiRmxpbnRTb2Z0LkNSTSIsImF1ZCI6IkZsaW50U29mdC5DUk0ifQ.F-suCW00HUBYZ1HOKk5juoWfBS49rlrk9TE0qr8Zgso